stages:
  build_features:
    cmd: python .\src\features\build_features.py .\data\raw\train.csv
    deps:
    - .\data\raw\train.csv
    - .\src\features\build_features.py
    outs:
    - .\data\build_data\

  make_dataset:
    cmd: python .\src\data\make_dataset.py .\data\build_data\processed.csv
    deps:
    - .\data\build_data\processed.csv
    - .\src\data\make_dataset.py
    params:
    - make_dataset.test_split
    - make_dataset.seed 

    outs:
    - .\data\processed\

  train_model:
    cmd: python .\src\models\train_model.py .\data\processed\
    deps:
    - .\data\processed\
    - .\src\models\train_model.py
    outs:
    - .\models\

  visualize:
    cmd: python .\src\visualization\visualize.py .\models\model.joblib .\data\processed\
    deps:
    - .\data\processed\
    - .\models\model.joblib
    - .\src\visualization\visualize.py 
   


    

