
name: DVC Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Install DVC
      run: |
        sudo apt-get update
        sudo apt-get install -y dvc

    - name: Configure DVC remote storage
      run: |
        dvc remote add -d myremote gdrive://1QuY-u0O6XSUt3OB4oeRuQzXLdI9EOJaX

    - name: Pull DVC data
      run: dvc pull

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run your DVC pipeline
      run: dvc repro




        
