name: DVC Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 
    - uses: actions/setup-python@v4

    - name: Install dependencies
      run: pip install -r requirements.txt  

    - name: Configure DVC remote storage
      run: |
        dvc remote add -d myremote gdrive://1QuY-u0O6XSUt3OB4oeRuQzXLdI9EOJaX

    - name: Set GDRIVE_CREDENTIALS_DATA as environment variable
      run: |
        echo ::set-env name=GDRIVE_CREDENTIALS_DATA::"${{ secrets.GDRIVE_CREDENTIALS_DATA }}"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          body: |
            Release notes for version 1.0.0
          draft: false
          prerelease: false


    - name: Pull DVC data
      run: dvc pull
    
    - name: Run your DVC pipeline
      run: dvc repro
