name: DVC Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Sanity check
        env:
          repo_token: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          # Add commands for the sanity check step

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure DVC remote storage
        run: |
          dvc remote add -d myremote gdrive://1QuY-u0O6XSUt3OB4oeRuQzXLdI9EOJaX

      - name: install dvc
        run: |
          pip install --upgrade dvc

      - name: install openssl
        run: |
          sudo apt-get update
          sudo apt-get install openssl    


      - name: Pull DVC data
        run: |
          dvc pull

      - name: Run your DVC pipeline
        run: |
          dvc repro

