name: DVC Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Sanity check
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA : ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          # Add commands for the sanity check step

      - name: Install dependencies
        run: |
          pip install -r requirements.txt



      - name: install dvc
        run: |
          pip install --upgrade dvc

      - name: install openssl
        run: |
          sudo apt-get update
          sudo apt-get install openssl
          pip install --upgrade pyOpenSSL
          pip install cryptography==38.0.4   


      - name: Pull DVC data
        run: |
          dvc pull

      - name: Run your DVC pipeline
        run: |
          dvc repro

        
          
